version: '3.5'

services: 
  postgres:
    image: postgres
    container_name: ms_postgress_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      #-e PGDATA="/pgdata", the database data will be written to /pgdata within the container. (если надо поменять default место сохранения)
      # by default postgrasql folder for data - /var/lib/postgresql/data/
      PGDATA: "/var/lib/postgresql/data/pgdata" #определяет место, где БД будет хранить данные.
    # связываем / корень vps и default path в docker container
    volumes: 
      - .:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    restart: unless-stopped
  
  
  
  
 

